apiVersion: v1
entries:
  neo4j-community:
  - apiVersion: v2
    appVersion: 4.2.4
    created: "2021-04-07T09:42:39.040289699Z"
    description: Neo4j is the world's leading graph database
    digest: b56cc24d7878fd00fef63667619e5aacd7031b4f889ef61c368cba675f5346f0
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/neo4j-contrib/neo4j-helm
    - https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community
    urls:
    - neo4j-community-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 4.2.4
    created: "2021-04-07T09:42:39.039211094Z"
    description: Neo4j is the world's leading graph database
    digest: 03fb501b7514110d0d1f2de0a7c249b53105ffa96b42975250ee4665bf36d99c
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/neo4j-contrib/neo4j-helm
    - https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community
    urls:
    - neo4j-community-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2021-04-07T09:42:39.038137488Z"
    description: Neo4j is the world's leading graph database
    digest: a9c333d15e9742f93b77dc1616687f602a47e11d6e23fae426180a88802b7ba1
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community
    urls:
    - neo4j-community-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2021-04-07T09:42:39.037430085Z"
    description: Neo4j is the world's leading graph database
    digest: 48de606dbb5c3f08b84570144b795f16d6365422b5e1cfcb8b5eb150e8a87b7d
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community
    urls:
    - neo4j-community-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2021-04-07T09:42:39.03647438Z"
    description: Neo4j is the world's leading graph database
    digest: 5b7b8e7ffcacfec129b30c14fcf101bb7ffc5e916d87da5ad00b67ea5dc784dd
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/charts/neo4j-community
    urls:
    - neo4j-community-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: 3.5.17
    created: "2021-04-07T09:42:39.035903377Z"
    description: Neo4j is the world's leading graph database
    digest: 1f9a6f47cdf98cbe54081f581bd607acab2549ea6531e9c17f46fbedce8f2547
    home: https://www.neo4j.com
    icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
    maintainers:
    - email: sovrevage@gmail.com
      name: StianOvrevage
    name: neo4j-community
    sources:
    - https://github.com/neo4j/neo4j
    - https://github.com/neo4j/docker-neo4j
    - https://github.com/mneedham/k8s-kubectl
    - https://github.com/equinor/helm-charts/charts/neo4j-community
    urls:
    - neo4j-community-1.0.2.tgz
    version: 1.0.2
generated: "2021-04-07T09:42:39.034919672Z"
